notifications:
 email:
  recipients:
   - pk.roger@icloud.com

language: python

python:
    - "3.6"

install:
    #    - sudo apt-get install -y python-virtualenv
      #    - sudo apt-get install -y python3-pip
    - git clone https://github.com/ISA-tools/isa-api.git
      #    - echo $PWD
      #    - sudo pip3 install -e $PWD/isa-api

branches:
  only:
    - master
    - develop

script:
    - make planemolint
# Planemo test works locally, but not on Travis-CI
#    - make planemotest
