dist: bionic

notifications:
 email:
  recipients:
   - pierrick.roger@cea.fr

language: python

python:
    - "3.8"

install:
    - sudo apt-get update
    - sudo apt-get install -y python3-pip python3-setuptools
    - pip3 install --user isatools

script:
    - make test
    - make plint
    - make ptest
