notifications:
 email:
  recipients:
   - pk.roger@icloud.com

language: python

python:
    - "3.6"

install:
    - git clone https://github.com/ISA-tools/isa-api.git
    - sudo pip3 install -e $PWD/isa-api

branches:
  only:
    - master
    - develop

script:
    - make planemolint
    - make planemotest
